BIVT-21-8_2_RobishAS_Project_Askme/Source/config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  resources :questions do
    put :hide, on: :member
  end

  resources :hashtags, param: :value, only: [:show]

  resource :session, only: %i[new create destroy]
  resources :users, param: :nickname, except: [:index]
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/models/hashtag.rb
class Hashtag < ApplicationRecord
  HASHTAG_PATTERN = /#[[:word:]]+/

  has_many :question_hashtags, dependent: :destroy
  has_many :questions, through: :question_hashtags

  def to_param
    value
  end
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/models/question.rb
class Question < ApplicationRecord
  after_commit :add_hashtags, on: [:create, :update]

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true
  validates :body, presence: true, length: {maximum: 280}

  has_many :question_hashtags, dependent: :destroy
  has_many :hashtags, through: :question_hashtags

  def hashtags_included
    "#{body} #{answer}".downcase.scan(Hashtag::HASHTAG_PATTERN).uniq
  end

  private

  def add_hashtags
    self.hashtags =
      hashtags_included.map { |hashtag| Hashtag.find_or_create_by(value: hashtag) }
  end
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/models/question_hashtag.rb
class QuestionHashtag < ApplicationRecord
  belongs_to :question
  belongs_to :hashtag
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/models/user.rb
class User < ApplicationRecord
  include Gravtastic

  has_secure_password
  has_many :questions, dependent: :destroy

  before_validation :downcase_nickname

  validates :email, presence: true, uniqueness: true,
            format: {with: URI::MailTo::EMAIL_REGEXP}
  validates :nickname, presence: true, uniqueness: true, length: {maximum: 40},
            format: { without: /\W/ }
  validates :header_color, format: { with: /\A#\h*\z/ }, length: { is: 7 }

  gravtastic(secure: true, filetype: :png, size: 100, default: 'mp')

  private

  def downcase_nickname
    nickname&.downcase!
  end
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  # GET /hashtags/1 or /hashtags/1.json
  def show
    @hashtag = Hashtag.find_by!(value: params[:value].downcase)
    @questions = @hashtag.questions.order(created_at: :desc)
  end
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[update destroy edit hide]
  before_action :set_question_for_current_user, only: %i[update destroy edit hide]

  def create
    question_params = params.require(:question).permit(:body, :user_id, :author_id)

    @question = Question.create(question_params)
    @question.author = current_user

    if @question.save
      redirect_to user_path(@question.user.nickname), notice: 'Новый вопрос создан!'
    else
      render :new
    end
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)
    @question.update(question_params)

    redirect_to user_path(@question.user.nickname), notice: 'Обновили вопрос!'
  end

  def hide
    @question.update(visible: false)

    redirect_to questions_path
  end

  def destroy
    @user = @question.user
    @question.destroy

    redirect_to user_path(@user.nickname), notice: 'Вопрос удален!'
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.order(created_at: :desc).first(10)
    @users = User.order(created_at: :desc).last(10)
    @hashtags = Hashtag.joins(:questions).distinct(:value).last(5)
  end

  def new
    @user = User.find(params[:user_id])
    @question = Question.new(user: @user)
  end

  def edit
  end

  private

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end

end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)
    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Вы вошли на сайт'
    else
      flash.now[:alert] = 'Неправильный email или пароль'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Вы вышли из аккаунта'
  end
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Вы успешно зарегистрировались'
    else
      flash.now[:alert] = "Вы неправильно заполнили поля формы регистрации :("
      render :new
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'Данные пользователя обновлены'
    else
      flash.now[:alert] = "При попытке сохранить пользователя возникли ошибки"
      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)
    redirect_to root_path, notice: 'Пользователь удалён'
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @question = Question.new(user: @user)
  end

  private
  def set_user
    @user = User.find_by(nickname: params[:nickname])
  end

  def authorize_user
    redirect_with_alert unless current_user == @user
  end

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :password, :password_confirmation, :header_color
    )
  end
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/helpers/hashtags_helper.rb
module HashtagsHelper
  def tags_to_links(string_hashtags)
    string_hashtags.map { |tag| link_to(tag, hashtag_path(tag)) }.join(", ")
  end
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/helpers/questions_helper.rb
module QuestionsHelper
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/helpers/users_helper.rb
module UsersHelper
  def wrap(username)
    "@#{username}"
  end
end

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/hashtags/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Хэштег <%= @hashtag.value %></h2>
</div>

<div class="mt-sm container">Все вопросы с этим хэштегом:</div>

<% @questions.each do |question| %>
  <div class="mt-sm container">
    <%= render question %>
  </div>
<% end %>

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <div class="navbar" style="background-color: <%= current_user.header_color if current_user.present? %>">
        <p class="text-sm text-bold"><%= link_to 'Ask me!', root_path %></p>
        <div>
          <% if current_user.present? %>
            <%= link_to wrap(current_user.nickname), user_path(current_user.nickname), class: 'mr-sm' %>
            <%= button_to 'Выйти', session_path, method: :delete, class: 'button button-main' %>
          <% else %>
            <%= link_to 'Регистрация', new_user_path, class: 'button button-yellow mr-sm' %>
            <%= link_to 'Вход', new_session_path, class: 'button button-yellow' %>
          <% end %>
        </div>
      </div>

      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert].present? %>
        <p class="mb mt message message-alert"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/questions/_form.html.erb
<%= form_with model: question, local: true do |form| %>
    <%= form.hidden_field :user_id %>

  <p><%= form.label :body, "Текст вопроса" %></p>
  <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

  <% if question.persisted? %>
    <p class="mt"><%= form.label :answer, 'Ответ' %></p>
    <p><%= form.text_area :answer, rows: 5, class: 'form-text-area' %></p>
  <% end %>

  <p><%= form.submit "Сохранить", class: 'button button-main' %>
    или
    <%= link_to "вернуться", "/" %>
  </p>
<% end %>

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/questions/_question.html.erb
<div class="mb-sm">
  <% if question.visible %>
    <%= simple_format h(question.body) %>
  <% else %>
    <div class="invisible">
      <%= simple_format h(question.body) %>
    </div>
  <% end %>
</div>

<% if question.answer.present? %>
  <div class="mb-sm text-dark-red">
    <%= question.answer %>
  </div>
<% end %>

<div class="text-sm question-footer">
  <div class="text-grey">
    <%= l(question.created_at, format: :short) %>, от:
    <% if question.author_id %>
      <%= link_to wrap(question.author.nickname), user_path(question.author.nickname) %>
    <% else %>
      Аноним
    <% end %>

    <% unless question.hashtags_included.empty? %>
      <%= simple_format tags_to_links(question.hashtags_included)  %>
    <% end %>
  </div>


  <% if current_user == question.user %>
    <div>
      <% if question.visible %>
        <%= button_to hide_question_path(question), method: :put, title: 'Скрыть вопрос' do %>
          <%= fa_icon('eye-slash') %>
        <% end %>
      <% end %>

      <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>
      <%= link_to fa_icon(edit_icon), edit_question_path(question),
          title: 'Изменить вопрос'%>

      <%= button_to question_path(question), method: :delete, title: 'Удалить вопрос',
                    data: {confirm: "Точно удалить вопрос?"} do %>
        <%= fa_icon('trash-o') %>
      <% end %>
    </div>
  <% end %>
</div>

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg">Редактирование вопроса <%= @question.id %></h2>

  <%= render 'form', question: @question %>
</div>

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/questions/index.html.erb
<div class="container">
  <h2 class="title-lg mb">
    Недавно добавились
  </h2>

  <div class="users-box">
    <% @users.each do |user| %>
      <%= render partial: 'users/user_avatar', locals: {user: user} %>
    <% end %>
  </div>
</div>

<div class="container mt-sm">
  <h2 class="title-lg">
    Последние хэштеги:
  </h2>
  <h3 class="title-sm index-tags">
    <% @hashtags.each do |tag| %>
      <p class="mr-sm">
        <%= simple_format link_to(tag.value, hashtag_path(tag)) %>
      </p>
    <% end %>
  </h3>
</div>

<div class="container mt-sm">
  <h2 class="title-lg">
    <%= inclination(@questions.count, 'Последний', 'Последние', 'Последние') %>
    <%= @questions.count %>
    <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
  </h2>
</div>

<% @questions.each do |question| %>
  <div class="mt-sm container">
    <p class="mb text-sm text-grey">
      Вопрос <%= link_to "##{question.id}", question_path(question) %>
      для юзера <%= link_to wrap(question.user.nickname), user_path(question.user.nickname) %>
    </p>

    <%= render partial: 'question', object: question %>
  </div>
<% end %>

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb-sm">Новый вопрос</h2>

  <p class="mb">для <%= link_to "@#{@question.user.nickname}", user_path(@question.user.nickname) %></p>

  <% if @question.errors.any? %>
    <div class="mt">
      <% @question.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <%= render 'form', question: @question %>
</div>

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Вопрос <%= @question.id %></h2>
  <p class="mt-sm"><%= link_to "Все вопросы @#{@question.user.nickname}", user_path(@question.user.nickname) %></p>
</div>

<div class="container mt-sm">
  <%= render 'question', question: @question %>
</div>

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/questions/update.html.erb
Ваш запрос обработан

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/users/_user_avatar.html.erb
<% background_class = "users-box-user-bg#{user.id % 5}" %>

<div class="users-box-user mr <%= background_class %> rounded">
  <a href="<%= user_path(user.nickname) %>">
    <%= image_tag user.gravatar_url, title: "@#{user.nickname}", class: 'rounded' %>
  </a>
</div>

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">Редактирование профиля</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <p><%= image_tag @user.gravatar_url, title: "@#{@user.nickname}", class: 'rounded' %></p>
    <p class="text-sm">Чтобы добавить или поменять аватар — зарегистрируйтесь на <%= link_to "Gravatar", 'https://gravatar.com' %> и загрузите фото</p>
  </div>

  <div class="mt">
    <%= form_with model: @user, url: user_path(params[:nickname]), local: true do |form| %>
      <p><%= form.label :name, 'Имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :header_color, 'Цвет шапки' %></p>
      <p><%= form.color_field :header_color, class: 'form-color-field' %>
      </p>

      <p class="mt-lg text-sm">Если не хотите менять пароль — оставьте эти поля пустыми!</p>

      <p class="mt"><%= form.label :password, 'Пароль' %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation, 'Подтверждение пароля' %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt-lg">
        <%= form.submit "Сохранить", class: 'button button-main' %>
        <span class="text-sm">или <%= link_to "вернуться", :back %></span>
      </p>
    <% end %>

    <div class="mt-lg">
      <%= button_to "Удалить профиль", user_path(params[:nickname]),
                    method: :delete,
                    form: {data: {confirm: "Вы точно хотите удалить свой профиль?"}},
                    class: 'text-red text-sm button button-main' %>
    </div>
  </div>
</div>

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Присоединяйся и спрашивай!</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, local: true do |form| %>
      <p><%= form.label :name, 'Ваше имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt-lg"><%= form.submit "Зарегистрироваться", class: 'button button-main mt-lg' %></p>
  <% end %>
  </div>
</div>

BIVT-21-8_2_RobishAS_Project_Askme/Source/app/views/users/show.html.erb
<div class="user-box">
  <h2 class="title-lg mt-lg"><%= @user.name %></h2>

  <div class="mt">
    <%= render partial: 'users/user_avatar', locals: {user: @user} %>
  </div>

  <p class="text-bold mt mb-lg">@<%= @user.nickname %></p>

  <% if current_user == @user %>
    <p class="mt mb-lg">
      <%= link_to fa_icon('pencil'), edit_user_path(@user.nickname) %>
    </p>
  <% end %>

</div>

<div class="container">
  <%= link_to 'Спроси меня', new_question_path(user_id: @user.id),
              class: 'button button-yellow' %>

  <p class="mt">
    <%= render 'questions/form', question: @question %>
  </p>
</div>

<div class="container mt-sm">
  <h2 class="title-lg">
    <%= @questions.count %>
    <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
  </h2>

  <% if @questions.count == 0 %>
    <p class="mt">У этого пользователя пока никто ничего не спросил...</p>
    <p class="mt-sm">Но вы легко можете это <%= link_to 'исправить',
                  new_question_path(user_id: @user.id)%>.</p>
  <% end %>
</div>

<% @questions.each do |question| %>
  <div class="mt-sm container">
    <%= render question %>
  </div>
<% end %>